# Generated by Django 5.2.9 on 2026-01-03 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConsents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("newsletter_consent", models.BooleanField(default=False)),
                ("newsletter_consent_at", models.DateTimeField(blank=True, null=True)),
                ("privacy_policy_consent", models.BooleanField(default=False)),
                ("privacy_policy_consent_at", models.DateTimeField(blank=True, null=True)),
                ("terms_of_service_consent", models.BooleanField(default=False)),
                ("terms_of_service_consent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
