# Generated by GitHub Copilot on 2026-01-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []
