# Generated by Django 5.2.9 on 2026-01-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_description_html_recipe_meta_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Ingredientų grupė",
                "verbose_name_plural": "Ingredientų grupės",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipe_ingredients",
                to="recipes.ingredientgroup",
            ),
        ),
    ]
