# Generated by Django 5.2.9 on 2026-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipeingredient_unique_by_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
