# Generated by Django 5.2.9 on 2026-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipestep_description_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
