# Generated by Django 5.2.9 on 2026-01-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_and_step_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
    ]
