# Generated by Django 5.2.9 on 2026-01-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_recipe_is_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="description_html",
        ),
        migrations.RemoveField(
            model_name="recipestep",
            name="description_html",
        ),
    ]
