# Generated by Django 5.2.9 on 2026-01-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_remove_recipe_description_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="nutrition",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="nutrition_dirty",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="nutrition_input_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="recipe",
            name="nutrition_last_enqueued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="nutrition_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RecipeNutritionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Eilėje"),
                            ("running", "Vykdoma"),
                            ("succeeded", "Pavyko"),
                            ("failed", "Nepavyko"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("input_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_jobs",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="recipes_rec_status_3d5af9_idx"
                    ),
                    models.Index(
                        fields=["recipe", "status", "created_at"],
                        name="recipes_rec_recipe__af54ec_idx",
                    ),
                ],
            },
        ),
    ]
