# Generated by Django 5.2.9 on 2026-01-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_recipe_nutrition_recipe_nutrition_dirty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipenutritionjob",
            name="openai_batch_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="recipenutritionjob",
            name="openai_batch_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipenutritionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Eilėje"),
                    ("submitted", "Pateikta (batch)"),
                    ("running", "Vykdoma"),
                    ("succeeded", "Pavyko"),
                    ("failed", "Nepavyko"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
