# Generated by Django 5.2.9 on 2026-01-04 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_recipenutritionjob_openai_batch_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeImageJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Eilėje"),
                            ("running", "Vykdoma"),
                            ("succeeded", "Pavyko"),
                            ("failed", "Nepavyko"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("result_image_url", models.URLField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_jobs",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_image_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="recipes_rec_status_8bb354_idx"
                    ),
                    models.Index(
                        fields=["recipe", "status", "created_at"],
                        name="recipes_rec_recipe__f0454a_idx",
                    ),
                ],
            },
        ),
    ]
